### ISSUE TITLE
示例代码书写有误

### ISSUE THREAD

**Issue by clojurie** [ikcamp/Koa-Node.js-Web-FE-Development#1]
[model/custom.js](https://github.com/ikcamp/Koa-Node.js-Web-FE-Development/blob/master/%E7%AC%AC6%E7%AB%A0/6.2.3/db/model/custom.js)

1、26行fullAddress的get方法中是应该是：**getDataValue** 而不是 **getDateValue**
2、40行 **sequelize.STRING** 写法有误应该是：**Sequelize.STRING**
如上代码会导致同步数据的时候出现：**Error: Unrecognized data type for field city**

3、另外[db/index.js](https://github.com/ikcamp/Koa-Node.js-Web-FE-Development/blob/master/%E7%AC%AC6%E7%AB%A0/6.2.3/db/index.js)中的第6行 **fulladdress** 和model定义中的 **fullAddress** 写的不一致

**Comment by zhouyao** [comment]
感谢指正
