### ISSUE TITLE
[BUG] 6.2.2 的define.js 代码中id: Sequelize.UUID, title: Sequelize.STRING, 有问题

### ISSUE THREAD

**Issue by ScGPS** [ikcamp/Koa-Node.js-Web-FE-Development#11]
Ref https://github.com/ikcamp/Koa-Node.js-Web-FE-Development/blob/master/%E7%AC%AC6%E7%AB%A0/6.2.2/define.js
```
应该把
id: Sequelize.UUID,
改成
    id: {
        type: Sequelize.UUID,
        primaryKey: true
    }

把
title: Sequelize.STRING,
改成
type: Sequelize.STRING,
```

**Comment by dail** [comment]
定义是可以简写的，参考[文档](http://docs.sequelizejs.com/)
定义主键确实是严谨一些

**Comment by dail** [comment]
感谢反馈，已在https://github.com/ikcamp/Koa-Node.js-Web-FE-Development/commit/e8fee76b5f2581669d09c326dfeedf1bfe65ae41中修复
