### ISSUE TITLE
[BUG] 6.2.2 的define.js 代码中timestamps: false导致query.js中Product的createdAt会失败

### ISSUE THREAD

**Issue by ScGPS** [ikcamp/Koa-Node.js-Web-FE-Development#12]
https://github.com/ikcamp/Koa-Node.js-Web-FE-Development/blob/master/%E7%AC%AC6%E7%AB%A0/6.2.2/define.js
![image](https://user-images.githubusercontent.com/10125111/58155850-58a37200-7ca7-11e9-81a1-f49fdac9b360.png)

https://github.com/ikcamp/Koa-Node.js-Web-FE-Development/blob/master/%E7%AC%AC6%E7%AB%A0/6.2.2/query.js
![image](https://user-images.githubusercontent.com/10125111/58155827-4aedec80-7ca7-11e9-9203-273a5bcb81c2.png)

**Comment by dail** [comment]
感谢指正该问题，已在https://github.com/ikcamp/Koa-Node.js-Web-FE-Development/commit/e8fee76b5f2581669d09c326dfeedf1bfe65ae41中修复
