### ISSUE TITLE
关于6.3.3节的建议

### ISSUE THREAD

**Issue by a501308061** [ikcamp/Koa-Node.js-Web-FE-Development#3]
《koa 与 nodejs》一书中第六章数据库6.3.3节代码不全，看得云里雾里的，上github才发现原来漏掉了代码中重要的部分。
1.文件的开头应该说明这个是哪个文件。现在的只能靠猜。。。
2.该节model/course.js书上的源码少了一大块。最后courseSchema连导出的对象中weekday字段都被省略掉了。导致下文中index.js难以读懂。

感谢ikcamp编写此书。

**Comment by dail** [comment]
受限于书的篇幅，因此对代码做了精简，很抱歉给你的阅读带来了不便。
